apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: neo4j-pvc
  name: ${neo4j_pvc_name}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${neo4j_storage_size}
  storageClassName: local-path
